# A list of perspectives with the format <RIR>.<AWS-Region> TODO link to pages.
perspectives:
  - us-east-2
  - us-west-2
  - eu-central-1
  - eu-west-1
  - ap-southeast-1
  - ap-northeast-1

# The default number of perspectives to use.
default-perspective-count: 6

caa-domains:
  - example-ca.example.com

absolute-max-attempts: 3

instances-per-region: 2

# Whether to run in a more permissive mode for development. Allows specification of named perspectives.
# False by default. If true, result should NOT be used for production MPIC.
# TODO align on naming and behavior (and where this kind of flag goes... API request or config here).
diagnostic-mode: false

# Whether to enforce whether two distinct RIR regions must succeed.
# TODO align on whether this flag is valid to even manage.
enforce-distinct-rir-regions: true
