# A list of perspectives with the format <RIR>.<AWS-Region> TODO link to pages.
perspectives:
  - arin.us-east-2
  - arin.us-west-2
  - ripe.eu-central-1

# The AWS region name for the API gateway and controller.
api-region: us-east-2

# The default number of perspectives to use.
default-perspective-count: 2

# Path to source code for the functions
source-path: /src/aws_lambda_mpic

caa-domains:
  - example-ca.example.com

absolute-max-attempts: 10

# Whether to run in a more permissive mode for development. Allows specification of named perspectives.
# False by default. If true, result should NOT be used for production MPIC.
# TODO align on naming and behavior (and where this kind of flag goes... API request or config here).
diagnostic-mode: false

# Whether to enforce whether two distinct RIR regions must succeed.
# TODO align on whether this flag is valid to even manage.
enforce-distinct-rir-regions: false
